# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83f7308880ab4186027c3b4d61dc21efaf4d5f6e52c9ca6c09a1c1c845337933333e2d2be1957d84dfa1bf7cbc6f0fa3657cdeae9e17da910ca9f534e5b02fbe

test:
  secret_key_base: c4439f2f0fdce8832be202cf371bdc14a2e817b25907db32c5cb0801e06f467174ca4576495b777d36ff9be0172041f76f8d1c596f710f0ab7562e10b9adafcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
